import { component$ } from "@builder.io/qwik";
import { css } from "styled-system/css";
import { FittingRoom } from "~/components/fitting/fitting-room";
import { CopyCommand } from "~/components/ui/copy-command";
import { DEMO_PERSONAS, DEMO_TOKENS } from "~/lib/demo-data";

export const HeroSection = component$(() => {
  return (
    <section
      id="fitting"
      aria-labelledby="hero-title"
      class={css({ maxW: "1240px", mx: "auto", px: { base: 4, md: 8 }, pt: { base: 12, md: 20 }, pb: { base: 16, md: 24 } })}
    >
      <div class={css({ display: "grid", gridTemplateColumns: { base: "minmax(0, 1fr)", xl: "minmax(0, 0.78fr) minmax(0, 1.4fr)" }, gap: { base: 12, xl: 12 }, alignItems: "center" })}>
        <div class={`rise ${css({ display: "flex", flexDirection: "column", gap: 6 })}`}>
          <span class="label" style={{ color: "#A9311E" }}>Persona-driven design generation</span>
          <h1
            id="hero-title"
            class="display"
            style={{ fontSize: "clamp(48px, 7.4vw, 104px)" }}
          >
            Cut to fit <em class={css({ fontStyle: "italic", color: "thread-ink" })}>one</em> person.
          </h1>
          <p class={css({ fontSize: { base: "18px", md: "20px" }, color: "ink-soft", maxW: "34ch", lineHeight: 1.5 })}>
            Generic interfaces fit everyone, so they fit no one. Baste takes a persona's films,
            music, rooms and obsessions, and from them drafts the design system, icons, images and
            motion that fit.
          </p>
          <div class={css({ display: "flex", flexWrap: "wrap", gap: 3, alignItems: "center" })}>
            <a
              href="/gui"
              data-juice="snip"
              class={css({
                display: "inline-flex", alignItems: "center", gap: 2, px: 5, h: "46px", rounded: "base",
                bg: "ink", color: "paper", fontWeight: 600, textDecoration: "none", transition: "background 0.2s",
                _hover: { bg: "thread-ink" },
              })}
            >
              Open the Studio <span aria-hidden="true">→</span>
            </a>
            <CopyCommand command="baste generate cyberbotanist --dry-run" />
          </div>
        </div>

        <div class={`rise ${css({ minW: 0 })}`} style={{ animationDelay: "120ms" }}>
          <FittingRoom personas={DEMO_PERSONAS} tokens={DEMO_TOKENS} />
          <p class={css({ mt: 4, fontSize: "13px", color: "ink-muted", maxW: "60ch" })}>
            Same screen, same code. Every colour, typeface, radius, spacing step and easing curve
            above was generated by Baste from the persona alone.
          </p>
        </div>
      </div>
    </section>
  );
});
