/** Account/onboarding copy is paired explicitly; existing global catalogs stay intact. */
const en = {
  title: 'Not Organic account', refresh: 'Refresh account', checking: 'Checking your Baste account…',
  demo: 'This is the browser demo. Account sign-in needs a connected Baste server.',
  minimum: 'Baste accounts are for people aged 14 or older. Higher local or provider requirements still apply.',
  unavailable: 'The account service is unavailable. Refresh or try again later.', setup: 'Account setup',
  notConfigured: 'Not Organic is not configured on this Baste server.', signDescription: 'Sign in at Not Organic. Baste checks its own age and account confirmations before opening your account workspace.',
  signin: 'Sign in / create profile', testSignin: 'Continue local test sign-in', signout: 'Sign out', signedout: 'Signed out of Baste',
  draft: 'These Baste policies are unpublished drafts. Real account acceptance is paused until the owner adopts and publishes the final copy.',
  prototype: 'Local test only. The policies are drafts; this records a preview receipt, not acceptance of effective terms.',
  termsLink: 'Read Baste Terms', privacyLink: 'Read Baste Privacy Policy', connected: 'Connected profile', manage: 'Manage profile at Not Organic ↗',
  gateTitle: 'Before opening your Baste account', gateIntro: 'Your identity is connected. Baste keeps account data, models, wallet and generation locked until you complete these confirmations.',
  saved: 'The Baste server saves the policy version, server date, language and these confirmations under your account. It does not ask for your birth date or an identity document. A checkbox is an attestation, not age verification.',
  loadingPolicy: 'Loading the complete Baste policy copies…', policyError: 'The current policies could not be loaded. Refresh before continuing.',
  frenchFirst: 'French Terms are provided first. You may read them below or open the complete policy page.', frenchLabel: 'French Terms supplied for this agreement',
  englishChoice: 'Choose English for this agreement', frenchChoice: 'Use the French Terms', englishLabel: 'English Terms — chosen for this agreement',
  age: 'I confirm that I am 14 or older.', termsFr: 'I agree to the French Baste Terms presented above.',
  termsEn: 'Having received the French Terms, I expressly choose to be bound by the English Baste Terms and agree to them.',
  processing: 'I consent to connecting my profile to Baste and storing my account designs and this receipt on the Baste server. If I request hosted generation or evaluation, my supplied design content is sent to the configured model services described in the Privacy Policy.',
  optional: 'This does not authorize optional analytics, advertising or a new processing purpose. Sending another person’s personal information requires appropriate authorization.',
  minors: 'Being 14 does not give adult contract capacity. Use a parent or tutor where the law requires their authorization or representation. These confirmations do not authorize a purchase or subscription.',
  accept: 'Confirm and open Baste', previewAccept: 'Confirm for this local test', decline: 'I do not agree — sign out', underage: 'I am under 14 — sign out',
  declined: 'Your Baste session has ended. No acceptance was recorded.', underageResult: 'Your Baste session has ended. Baste accounts require age 14 or older.',
  saveError: 'Your confirmations were not saved. Refresh, review the current policies and try again.', saving: 'Saving your confirmations…',
  completion: 'Baste confirmations saved', receipt: 'Current Baste confirmations saved', version: 'Policy version', acceptedDate: 'Server-recorded date',
  updateServer: 'This Baste server needs the versioned account gate before its account workspace can open.',
  wallet: 'Wallet', walletError: 'Balance unavailable.', noBalance: 'The available balance could not be verified.', available: 'available for hosted generation',
  blocked: 'Hosted inference is blocked by your wallet. Review billing at Not Organic before generating.', empty: 'Add credit before requesting paid generation. Prompt drafts remain available.',
  checkoutUnavailable: 'Checkout is unavailable. Refresh later, or manage your account at Not Organic.', purchase: 'The payment page shows the current price before you pay. Returning here does not confirm payment; refresh your wallet.',
  buy: 'Buy credit', plan: 'View plan', noOffers: 'No offers are currently available for this account.', models: 'Hosted models', modelError: 'Catalog unavailable.', noModels: 'No hosted models are available to this account.',
  providers: 'Images use the live catalog. SVGs and videos use your configured local providers. Provider credentials stay on the Baste server.',
  accountError: 'Sign-in could not be completed. Try again.', onboardingToast: 'Complete your Baste confirmations to open your account.', connectedToast: 'Connected to Baste',
};
const fr: Record<keyof typeof en, string> = {
  title: 'Compte Not Organic', refresh: 'Actualiser le compte', checking: 'Vérification de votre compte Baste…',
  demo: 'Vous utilisez la démonstration dans le navigateur. La connexion à un compte exige un serveur Baste connecté.',
  minimum: 'Les comptes Baste sont réservés aux personnes de 14 ans ou plus. Les exigences locales ou des fournisseurs plus élevées restent applicables.',
  unavailable: 'Le service de compte est indisponible. Actualisez ou réessayez plus tard.', setup: 'Configuration du compte',
  notConfigured: 'Not Organic n’est pas configuré sur ce serveur Baste.', signDescription: 'Connectez-vous chez Not Organic. Baste vérifie ses propres confirmations d’âge et de compte avant d’ouvrir votre espace.',
  signin: 'Se connecter / créer un profil', testSignin: 'Continuer la connexion de test locale', signout: 'Se déconnecter', signedout: 'Déconnexion de Baste effectuée',
  draft: 'Ces politiques Baste sont des projets non publiés. L’acceptation réelle est suspendue jusqu’à l’adoption et à la publication des textes définitifs par le propriétaire.',
  prototype: 'Test local uniquement. Les politiques sont des projets; cet enregistrement de test ne constitue pas l’acceptation de conditions en vigueur.',
  termsLink: 'Lire les conditions Baste', privacyLink: 'Lire la politique de confidentialité Baste', connected: 'Profil connecté', manage: 'Gérer le profil chez Not Organic ↗',
  gateTitle: 'Avant d’ouvrir votre compte Baste', gateIntro: 'Votre identité est connectée. Baste bloque les données du compte, les modèles, le portefeuille et la génération jusqu’à ces confirmations.',
  saved: 'Le serveur Baste enregistre la version des politiques, la date du serveur, la langue et ces confirmations dans votre compte. Aucune date de naissance ni pièce d’identité n’est demandée. Une case cochée est une attestation, pas une vérification de l’âge.',
  loadingPolicy: 'Chargement des textes complets des politiques Baste…', policyError: 'Les politiques actuelles n’ont pas pu être chargées. Actualisez avant de continuer.',
  frenchFirst: 'Les conditions françaises sont fournies en premier. Lisez-les ci-dessous ou ouvrez la page complète.', frenchLabel: 'Conditions françaises fournies pour cet accord',
  englishChoice: 'Choisir l’anglais pour cet accord', frenchChoice: 'Utiliser les conditions françaises', englishLabel: 'Conditions anglaises — choisies pour cet accord',
  age: 'Je confirme avoir 14 ans ou plus.', termsFr: 'J’accepte les conditions Baste françaises présentées ci-dessus.',
  termsEn: 'Après avoir reçu les conditions françaises, je choisis expressément d’être lié par les conditions Baste anglaises et je les accepte.',
  processing: 'Je consens à relier mon profil à Baste et à enregistrer mes créations de compte et cette confirmation sur le serveur Baste. Si je demande une génération ou une évaluation hébergée, mon contenu de conception est transmis aux services de modèles configurés décrits dans la politique de confidentialité.',
  optional: 'Cela n’autorise ni analyse facultative, ni publicité, ni nouvelle finalité de traitement. La transmission de renseignements personnels d’une autre personne exige une autorisation appropriée.',
  minors: 'Avoir 14 ans ne donne pas la capacité contractuelle d’un adulte. Faites intervenir un parent ou un tuteur lorsque la loi exige son autorisation ou sa représentation. Ces confirmations n’autorisent aucun achat ni abonnement.',
  accept: 'Confirmer et ouvrir Baste', previewAccept: 'Confirmer pour ce test local', decline: 'Je refuse — me déconnecter', underage: 'J’ai moins de 14 ans — me déconnecter',
  declined: 'Votre session Baste a pris fin. Aucune acceptation n’a été enregistrée.', underageResult: 'Votre session Baste a pris fin. Les comptes Baste exigent au moins 14 ans.',
  saveError: 'Vos confirmations n’ont pas été enregistrées. Actualisez, relisez les politiques actuelles et réessayez.', saving: 'Enregistrement de vos confirmations…',
  completion: 'Confirmations Baste enregistrées', receipt: 'Confirmations Baste actuelles enregistrées', version: 'Version des politiques', acceptedDate: 'Date enregistrée par le serveur',
  updateServer: 'Ce serveur Baste doit intégrer le contrôle de compte versionné avant d’ouvrir l’espace de compte.',
  wallet: 'Portefeuille', walletError: 'Solde indisponible.', noBalance: 'Le solde disponible n’a pas pu être vérifié.', available: 'disponibles pour la génération hébergée',
  blocked: 'Votre portefeuille bloque l’inférence hébergée. Vérifiez la facturation chez Not Organic avant de générer.', empty: 'Ajoutez du crédit avant de demander une génération payante. Les brouillons de prompts restent disponibles.',
  checkoutUnavailable: 'Le paiement est indisponible. Actualisez plus tard ou gérez votre compte chez Not Organic.', purchase: 'La page de paiement indique le prix actuel avant tout paiement. Le retour ici ne confirme pas le paiement; actualisez le portefeuille.',
  buy: 'Acheter du crédit', plan: 'Voir le forfait', noOffers: 'Aucune offre n’est actuellement disponible pour ce compte.', models: 'Modèles hébergés', modelError: 'Catalogue indisponible.', noModels: 'Aucun modèle hébergé n’est disponible pour ce compte.',
  providers: 'Les images utilisent le catalogue réel. Les SVG et vidéos utilisent vos fournisseurs locaux configurés. Les identifiants des fournisseurs restent sur le serveur Baste.',
  accountError: 'La connexion n’a pas pu être terminée. Réessayez.', onboardingToast: 'Complétez vos confirmations Baste pour ouvrir votre compte.', connectedToast: 'Connexion à Baste effectuée',
};
export const accountCopy = { en, fr };
